[package]
name = "quadbtree"
version = "0.1.0"
edition = "2018"

[dependencies]
smallvec="1.6"
savefile = "0.17"
savefile-derive = "0.17"
indexmap="1.9"
[dev-dependencies]
rand = "0.8"
rand_pcg = "0.3"
